export type PartId = 'body'|'glass'|'doors'|'cabin'|'battery'|'drive'|'suspension'|'wheels';
const manual = 'https://www.tesla.com/ownersmanual/modelx/en_us/';
export const parts: {id:PartId;name:string;category:string;tag:string;description:string;principle:string;specs:[string,string][];source:string}[] = [
{id:'body',name:'Body & structure',category:'Exterior',tag:'THE PROTECTIVE SHELL',description:'The body brings the vehicle together: an enclosed passenger space, crumple zones at either end, and a smooth exterior that guides air around the car.',principle:'The structure carries loads around the cabin, while the hood and liftgate give access to separate front and rear storage areas.',specs:[['Role','Structure & protection'],['Location','Vehicle exterior']],source:manual+'GUID-7A32EC01-A17E-42CC-A15B-2E0A39FD07AB.html'},
{id:'glass',name:'Panoramic glass',category:'Exterior',tag:'A WIDER VIEW',description:'The expansive windshield sweeps up above the front seats, opening the cabin to more of the world outside.',principle:'The windshield and side glazing create visibility around the vehicle. The overhead glass sections move with the falcon wing doors.',specs:[['Role','Visibility & enclosure'],['Position','Upper cabin']],source:manual+'GUID-F617DA3E-11C1-4FBA-98A7-A9C3828E3536.html'},
{id:'doors',name:'Falcon wing doors',category:'Exterior',tag:'ENGINEERING THAT OPENS UP',description:'Two hinges give each rear door its distinctive upward motion. The door folds as it rises, making access possible in tighter spaces.',principle:'Sensors check for obstacles while the powered hinges coordinate the opening path. Available clearance influences how high the door opens.',specs:[['Motion','Dual-hinged'],['Operation','Electrically powered']],source:manual+'GUID-7A32EC01-A17E-42CC-A15B-2E0A39FD07AB.html'},
{id:'cabin',name:'Passenger cabin',category:'Interior',tag:'BUILT AROUND PEOPLE',description:'The passenger space sits above the battery. Seats, restraints, controls and displays form the part of the vehicle you interact with every day.',principle:'A flat electric platform leaves room for multiple seating configurations. This study shows a simplified six-seat layout; actual seating varies by configuration.',specs:[['Shown here','Six-seat study'],['Position','Above battery']],source:manual+'GUID-F617DA3E-11C1-4FBA-98A7-A9C3828E3536.html'},
{id:'battery',name:'High-voltage battery',category:'Energy',tag:'THE ENERGY FOUNDATION',description:'A liquid-cooled lithium-ion battery stores the energy that powers the vehicle. Positioned beneath the cabin, it supplies the electric drive units.',principle:'Electrical energy flows to the motors during acceleration. During regenerative braking, the motors can convert vehicle motion back into energy stored in the battery.',specs:[['Chemistry','Lithium-ion'],['Nominal voltage','407 V DC'],['Cooling','Liquid-cooled']],source:manual+'GUID-E414862C-CFA1-4A0B-9548-BE21C32CAA58.html'},
{id:'drive',name:'Electric drive units',category:'Powertrain',tag:'ENERGY INTO MOTION',description:'Electric motors turn stored energy into wheel torque. This dual-motor study places one drive unit at the front and another at the rear.',principle:'An inverter controls each motor, and a fixed-ratio gearbox transfers rotation to the wheels. The motors also help slow the vehicle through regenerative braking.',specs:[['Layout','Front + rear'],['Transmission','Single-speed'],['Configuration','Dual motor']],source:manual+'GUID-E414862C-CFA1-4A0B-9548-BE21C32CAA58.html'},
{id:'suspension',name:'Adaptive suspension',category:'Chassis',tag:'CONNECTED TO THE ROAD',description:'Air springs support the car while adaptive dampers control body movement. The system can adjust ride height and the way the car responds to the road.',principle:'Front double-wishbone and rear multi-link suspension guide each wheel. Air pressure changes support height, while damping balances comfort with control.',specs:[['Springs','Air'],['Damping','Adaptive'],['Height','Adjustable']],source:manual+'GUID-F1B6801A-8946-41AD-8CF9-7A963CDA38E4.html'},
{id:'wheels',name:'Wheels & brakes',category:'Chassis',tag:'WHERE MOTION MEETS GRIP',description:'The tires are the vehicle’s contact with the road. Behind each wheel, a ventilated brake disc and caliper provide friction braking.',principle:'Regenerative braking recovers energy through the motors. Friction brakes provide additional stopping force, with ABS helping control wheel slip.',specs:[['Brakes','Ventilated discs'],['Control','Four-wheel ABS'],['Energy recovery','Regenerative braking']],source:manual+'GUID-E414862C-CFA1-4A0B-9548-BE21C32CAA58.html'},
];
